spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:sqlite:/data/client.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
server:
  port: 8085
resilience4j:
  circuitbreaker:
    instances:
      jmsSender:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
      personalInfoFetcher:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    tags:
      application: storage-service
logging:
  level:
    com.example: INFO
