spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
server:
  port: 8082
resilience4j:
  circuitbreaker:
    instances:
      jmsSender:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
      personalInfoFetcher:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    tags:
      application: address-service
logging:
  level:
    com.example: INFO